[package]
name = "changeup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
dbus = "0.9.5"
dbus-crossroads = "0.5.0"
dbus-tokio = "0.7.5"
env_logger = "0.9.0"
futures = "0.3.21"
log = "0.4.16"
swayipc-async = "2.0.0"
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
